apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: cd-jenkins
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-1.7.3
  name: cd-jenkins-7f9c84f9cb-nwgwz
  namespace: default
spec:
  containers:
  - args:
    - --argumentsRealm.passwd.$(ADMIN_USER)=$(ADMIN_PASSWORD)
    - --argumentsRealm.roles.$(ADMIN_USER)=admin
    env:
    - name: JAVA_OPTS
    - name: JENKINS_OPTS
    - name: JENKINS_SLAVE_AGENT_PORT
      value: "50000"
    - name: ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          key: jenkins-admin-password
          name: cd-jenkins
    - name: ADMIN_USER
      valueFrom:
        secretKeyRef:
          key: jenkins-admin-user
          name: cd-jenkins
    image: jenkins/jenkins:lts
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /login
        port: http
        scheme: HTTP
      initialDelaySeconds: 90
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: jenkins
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 50000
      name: slavelistener
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /login
        port: http
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 50m
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/jenkins_home
      name: jenkins-home
    - mountPath: /var/jenkins_config
      name: jenkins-config
      readOnly: true
    - mountPath: /usr/share/jenkins/ref/secrets/
      name: secrets-dir
    - mountPath: /usr/share/jenkins/ref/plugins/
      name: plugin-dir
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - sh
    - /var/jenkins_config/apply_config.sh
    env:
    - name: ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          key: jenkins-admin-password
          name: cd-jenkins
    - name: ADMIN_USER
      valueFrom:
        secretKeyRef:
          key: jenkins-admin-user
          name: cd-jenkins
    image: jenkins/jenkins:lts
    imagePullPolicy: Always
    name: copy-default-config
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 50m
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/jenkins_home
      name: jenkins-home
    - mountPath: /var/jenkins_config
      name: jenkins-config
    - mountPath: /usr/share/jenkins/ref/secrets/
      name: secrets-dir
    - mountPath: /usr/share/jenkins/ref/plugins
      name: plugins
    - mountPath: /var/jenkins_plugins
      name: plugin-dir
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsUser: 0
  serviceAccount: cd-jenkins
  serviceAccountName: cd-jenkins
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: plugins
  - emptyDir: {}
    name: tmp
  - configMap:
      defaultMode: 420
      name: cd-jenkins
    name: jenkins-config
  - emptyDir: {}
    name: secrets-dir
  - emptyDir: {}
    name: plugin-dir
  - name: jenkins-home
    persistentVolumeClaim:
      claimName: cd-jenkins
